version: '3.8'

services:
  ssh-collector:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: ssh-collector
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # 基础配置
      - APP_NAME=SSH采集器
      - APP_VERSION=1.0.0
      - DEBUG=false
      - LOG_LEVEL=INFO
      
      # 服务配置
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8000
      - COLLECTOR_ID=collector-001
      
      # 数据库配置
      - DATABASE_URL=sqlite:///data/collector.db
      
      # 控制器配置（可选）
      - CONTROLLER_URL=http://controller:9000
      - CONTROLLER_ENABLED=false
      
      # 消息队列配置（可选）
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_ENABLED=false
      
      # 安全配置
      - MAX_CONNECTIONS=100
      - CONNECTION_TIMEOUT=30
      - COMMAND_TIMEOUT=300
      
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - ssh-collector-network
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: ssh-collector-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ssh-collector
    networks:
      - ssh-collector-network
    profiles:
      - nginx

networks:
  ssh-collector-network:
    driver: bridge